import type { Metadata } from 'next';
import { Provider } from '@/components/ui/provider';
import Menu from '@/components/menu';
import { Container } from '@chakra-ui/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <Provider>
          <Menu />
          <Container maxW={'lg'} py={'5'}>{children}</Container>
        </Provider>
      </body>
    </html>
  );
}
